config/routes.rb
Rails.application.routes.draw do
  get 'app/index'

  resources :budgets do
	  resources :budget_categories, controller: 'budget_category'
	end

  root 'app#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord

	has_many :budget_categories, dependent: :destroy
	accepts_nested_attributes_for :budget_categories #, update_only: true

	validates_presence_of :name
	validates_uniqueness_of :name # will later need to scope these to "accounts"

	def update_budget_categories(budget_categories_params)
		return if budget_categories_params.nil?

		budget_categories_params.each do |index|
			budget_category = BudgetCategory.find(budget_categories_params[index]["id"])
			budget_category.amount = budget_categories_params[index]["amount"]
			budget_category.save
		end
	end
end

app/models/budget_category.rb
class BudgetCategory < ApplicationRecord

	belongs_to :budget

end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/budget_category_controller.rb
class BudgetCategoryController < ApplicationController
	before_action :load_budget_category, only: [:show]
	before_action :load_budget, only: [:create]

	def show
	end

	def new
		@budget_category = BudgetCategory.new
	end

	def create
		@budget_category = BudgetCategory.new(budget_category_params)

		@budget_category.budget = @budget

		if @budget_category.save
			redirect_to budget_path(@budget)
		else
			render 'new'
		end
	end

	private

	def load_budget_category
		@budget_category = BudgetCategory.find(params[:id])
	end

	def load_budget
		@budget = Budget.find(params[:budget_id])
	end

	def budget_category_params
		params.require(:budget_category).permit(:name, :amount)
	end

end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
	before_action :load_budget, only: [:show, :edit, :update]

	def show
	end

	def index
		@budgets = Budget.all
	end

	def new
		@budget = Budget.new
	end

	def create
		@budget = Budget.new(budget_params)

		if @budget.save
			redirect_to @budget
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		@budget.update_budget_categories(params[:budget][:budget_categories_attributes])

    if @budget.update(budget_params)
      redirect_to @budget
    else
      render 'edit'
    end
	end

	private

	def budget_params
    params.require(:budget).permit(:name, :budget_categories)
  end

  def load_budget
  	@budget = Budget.find(params[:id])
	end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budget_category_helper.rb
module BudgetCategoryHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/app/index.html.erb
<h1>App#index</h1>
<p>Find me in app/views/app/index.html.erb</p>
<%= link_to 'Budgets', controller: 'budgets' %>

app/views/budget_category/new.html.erb
<h2>BudgetCategory#new</h2>


<%= form_with scope: :budget_category, url: budget_budget_categories_path, local: true do |form| %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :amount %><br>
    <%= form.text_field :amount %>
  </p>
 
  <p>
    <%= form.submit "Save" %>
  </p>
<% end %>

app/views/budgets/edit.html.erb
<h2>Editing <%= @budget.name %>...</h2>
<%= button_to 'Back', budget_path(@budget), method: :get, class: "back-btn" %>

<div>
	<%= form_for @budget, url: budget_path, local: true do |form| %>
		
		<% if @budget.errors.any? %>
	    <div id="error_explanation">
	      <h2>
	        <%= pluralize(@budget.errors.count, "error") %> prohibited
	        this budget from being saved:
	      </h2>
	      <ul>
	        <% @budget.errors.full_messages.each do |msg| %>
	          <li><%= msg %></li>
	        <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <% if @budget.budget_categories.present? %>
		  <h4>Budget Categories:</h4>

	  	<% @budget.budget_categories.each do |budget_category| %>
			  <%= form.fields_for :budget_categories, budget_category do |categories_form| %>
				  <%= budget_category.name %>: <%= categories_form.text_field :amount %><br>
		    <% end %>
	    <% end %>
	  <% end %>

	  <p>
	    <%= form.label :name %><br>
	    <%= form.text_field :name %>
	  </p>
	 
	  <p>
	    <%= form.submit "Save" %>
	  </p>
	<% end %>
</div>

app/views/budgets/index.html.erb
<div>
	<h1>Budget#index</h1>

	<% @budgets.each do |budget| %>
		<div>
			<%= link_to budget.name, budget_path(budget) %>
		</div>
	<% end %>

	<%= button_to "New", new_budget_path, method: :get %>
</div>

app/views/budgets/new.html.erb
<h2>Budgets New Page</h2>
<%= button_to 'Back', budgets_path, method: :get, class: "back-btn" %>

<%= form_with scope: :budget, url: budgets_path, local: true do |form| %>
	
	<% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@budget.errors.count, "error") %> prohibited
        this budget from being saved:
      </h2>
      <ul>
        <% @budget.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.submit "Save" %>
  </p>
<% end %>

app/views/budgets/show.html.erb
<div>
	<span>
		<h2 class="budget-name">
			<%= @budget.name %>
		</h2>
		<%= button_to 'Edit', edit_budget_path, method: :get, class: "edit-btn" %>
		<%= button_to 'Back', budgets_path, method: :get, class: "back-btn" %>
	</span>

	<div class="categories">
		<h4>Proposed Budget Values:</h4>
		<ul>
			<% if @budget.budget_categories.empty? %>
				<code>You do not have any categories defined.</code>
			<% else %>
				<% @budget.budget_categories.each do |budget_category| %>
					<span>
						<li>
							<%= budget_category.name %>: $<%= budget_category.amount || "0.00" %>
						</li>
					</span>
				<% end %>
			<% end %>
		</ul>
		<%= button_to 'Add Category', new_budget_budget_category_path(@budget), method: :get %>
	</div>

	<div>
		<code>CSV uploads maybe here? How will we handle compiling uploads?</code>
	</div>

	<div>
		<code>Graphs can go here?</code>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetMaker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>